// Package json2define turns arbitrary JSON into compilable Go
// initialization code.
//
// The target Go type is supplied through reflection, so the generated
// composite literal is guaranteed to use the field names and field types
// of that type. The result is a complete, gofmt-ed source file that can be
// dropped into a package and compiled as-is.
package json2define

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"reflect"
	"strings"
)

// Generator holds the configuration and the state used to build Go source.
//
// A Generator is not safe for concurrent use; create one per generation
// with [New].
type Generator struct {
	packageName string
	varName     string
	samePkg     string

	imports *importManager
}

// Option customizes a [Generator].
type Option func(*Generator)

// WithPackageName sets the package clause of the generated file.
// The default is "main".
func WithPackageName(name string) Option {
	return func(g *Generator) { g.packageName = name }
}

// WithVarName sets the name of the generated variable. The default is
// "value".
func WithVarName(name string) Option {
	return func(g *Generator) { g.varName = name }
}

// WithSamePackagePath marks pkgPath as the package that will contain the
// generated file. Types declared in that package are emitted without a
// package qualifier and are not imported.
func WithSamePackagePath(pkgPath string) Option {
	return func(g *Generator) { g.samePkg = pkgPath }
}

// New returns a Generator configured with opts.
func New(opts ...Option) *Generator {
	g := &Generator{
		packageName: "main",
		varName:     "value",
		imports:     newImportManager(),
	}
	for _, opt := range opts {
		opt(g)
	}
	return g
}

// Generate builds a complete, gofmt-ed Go source file declaring a variable
// of type t initialized from data.
func (g *Generator) Generate(t reflect.Type, data []byte) (string, error) {
	if t == nil {
		return "", errors.New("json2define: nil target type")
	}
	value, err := g.decode(data)
	if err != nil {
		return "", err
	}
	expr, err := g.buildExpr(t, value)
	if err != nil {
		return "", err
	}
	typeName := g.typeString(t)

	var b strings.Builder
	b.WriteString("// Code generated by json2define; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", g.packageName)
	if imports := g.imports.render(); imports != "" {
		b.WriteString(imports)
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "var %s %s = %s\n", g.varName, typeName, expr)

	src := b.String()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return src, fmt.Errorf("json2define: generated source is invalid: %w", err)
	}
	return string(formatted), nil
}

// Generate creates a new Generator configured with opts and generates a
// variable of type t from data.
func Generate(t reflect.Type, data []byte, opts ...Option) (string, error) {
	return New(opts...).Generate(t, data)
}

// GenerateFor creates a new Generator configured with opts and generates a
// variable of type T from data.
func GenerateFor[T any](data []byte, opts ...Option) (string, error) {
	return Generate(reflect.TypeOf((*T)(nil)).Elem(), data, opts...)
}

func (g *Generator) decode(data []byte) (any, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	var v any
	if err := dec.Decode(&v); err != nil {
		return nil, fmt.Errorf("json2define: invalid JSON: %w", err)
	}
	if dec.More() {
		return nil, errors.New("json2define: unexpected trailing data after JSON value")
	}
	return v, nil
}
